export const products = [{
        cat: "hats",
        data: [{
                id: 0,
                title: "Personalized long strap black baseball hat",
                price: 12.99,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/hats/hats000.jpg",
            },

            {
                id: 1,
                title: "Graffiti printe hats",
                price: 12.99,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/hats/hats001.jpg",
            },

            {
                id: 2,
                title: "Sun visor baseball Cap",
                price: 12.99,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/hats/hats002.jpg",
            },

            {
                id: 3,
                title: "Sport Fashion Emroidery Caps",
                price: 7.91,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/hats/hats004.jpg",
            },

            {
                id: 4,
                title: "Sad Face Embroidery Baseball Hat",
                price: 5.29,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/hats/hats005.jpg",
            },
            {
                id: 5,
                title: "Fashion all-match sucreen hat",
                price: 12.67,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/hats/hats006.jpg",
            },
            {
                id: 6,
                title: "Washed Old Baseball Cap",
                price: 7.52,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/hats/hats007.jpg",
            },
            {
                id: 7,
                title: "Fashion Street Hip-hop Poker Hats",
                price: 8.0,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/hats/hats008.jpg",
            },
            {
                id: 8,
                title: "Corduroy Baseball Cap",
                price: 7.52,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/hats/hats009.jpg",
            },
            {
                id: 9,
                title: "Embroidered Baseball Caap",
                price: 5.04,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/hats/hats010.jpg",
            },
        ],
    },
    {
        cat: "books",
        data: [{
                id: 0,
                title: "Season Guide",
                price: 10.12,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/books/books001.jpg",
            },

            {
                id: 1,
                title: "Programma stagione",
                price: 15.59,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/books/books002.jpg",
            },

            {
                id: 2,
                title: "Un Ballo In Maschera",
                price: 12.99,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/books/books003.jpg",
            },

            {
                id: 3,
                title: "Pagliacci",
                price: 7.91,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/books/books004.jpg",
            },

            {
                id: 4,
                title: "Madama Butterfly",
                price: 5.29,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/books/books005.jpg",
            },
            {
                id: 5,
                title: "Lo Schiaccianoci",
                price: 12.67,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/books/books006.jpg",
            },
            {
                id: 6,
                title: "Les Contes D'DOFFMANN",
                price: 7.52,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/books/books007.jpg",
            },
            {
                id: 7,
                title: "La Boheme",
                price: 8.0,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/books/books008.jpg",
            },
            {
                id: 8,
                title: "Kata Kabanova",
                price: 7.52,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/books/books009.jpg",
            },
            {
                id: 9,
                title: "Die Walkire",
                price: 5.04,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/books/books010.jpg",
            },
        ],
    },
    {
        cat: "bags",
        data: [{
                id: 0,
                title: "Crossbody Bag(Blown)",
                price: 10.12,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/bags/bags001.png",
            },

            {
                id: 1,
                title: "Crossbody Bag(lightPink)",
                price: 15.59,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/bags/bags002.png",
            },

            {
                id: 2,
                title: "Double Pocket Tote Bag",
                price: 12.99,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/bags/bags003.png",
            },

            {
                id: 3,
                title: "Double Pkt Large Crossbody Bag",
                price: 7.91,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/bags/bags004.png",
            },

            {
                id: 4,
                title: "Weave Panel Shoulder Bag",
                price: 5.29,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/bags/bags005.png",
            },
            {
                id: 5,
                title: "Weave Panel Large Shoulder Bag",
                price: 12.67,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/bags/bags006.png",
            },
            {
                id: 6,
                title: "Hensely To Zip Shoulder Bag",
                price: 7.52,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/bags/bags007.png",
            },
            {
                id: 7,
                title: "Hensely Logo Shooper Bag",
                price: 8.0,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/bags/bags008.png",
            },
            {
                id: 8,
                title: "Wessex Triple Comp Shopper Bag",
                price: 7.52,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/bags/bags009.png",
            },
            {
                id: 9,
                title: "Weave Panel Crossbody Bag",
                price: 5.04,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeat esse.",
                img: "img/bags/bags010.png",
            },
        ],
    },
    {
        cat: "handmades",
        data: [{
                id: 0,
                title: "Wall Macrame Plant Hanger",
                price: 10.12,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeasse.",
                img: "img/handmades/handmades001.jpg",
            },

            {
                id: 1,
                title: "Wooden Bead Bracelet",
                price: 15.59,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeasse.",
                img: "img/handmades/handmades002.jpg",
            },

            {
                id: 2,
                title: "Rattan Straw Purse Summer Beach HandBags",
                price: 12.99,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeasse.",
                img: "img/handmades/handmades003.jpg",
            },

            {
                id: 3,
                title: "Hot Sale Vintage",
                price: 7.91,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeasse.",
                img: "img/handmades/handmades004.jpg",
            },

            {
                id: 4,
                title: "Dream Catcher",
                price: 5.29,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeasse.",
                img: "img/handmades/handmades005.jpg",
            },
            {
                id: 5,
                title: "Magnetic Titanium Leather Weave",
                price: 12.67,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeasse.",
                img: "img/handmades/handmades006.jpg",
            },
            {
                id: 6,
                title: "White Motorcycle Model",
                price: 7.52,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeasse.",
                img: "img/handmades/handmades007.jpg",
            },
            {
                id: 7,
                title: "Macrane Waven Wall Hanging Angel Wings",
                price: 8.0,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeasse.",
                img: "img/handmades/handmades008.jpg",
            },
            {
                id: 8,
                title: "Fabric Home Deccor Holloween Pumpkin",
                price: 7.52,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeasse.",
                img: "img/handmades/handmades009.jpg",
            },
            {
                id: 9,
                title: "Iron Shape Wall Hanging Decor ",
                price: 5.04,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates placeasse.",
                img: "img/handmades/handmades010.jpg",
            },
        ],
    },
    {
        cat: "others",
        data: [{
                id: 0,
                title: "New Technology Anti-odor Built-in Stroage Trash Can",
                price: 10.12,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates ceat esse.",
                img: "img/others/others001.jpg",
            },

            {
                id: 1,
                title: "8000mah Wireless Charging PowerBanks",
                price: 15.59,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates ceat esse.",
                img: "img/others/others002.jpg",
            },

            {
                id: 2,
                title: "Winslow & Ross Carbon Steel Spade",
                price: 12.99,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates ceat esse.",
                img: "img/others/others003.jpg",
            },

            {
                id: 3,
                title: "Plants 7 Piect Gradening Tool",
                price: 7.91,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates ceat esse.",
                img: "img/others/others004.png",
            },

            {
                id: 4,
                title: "Sachet filling machine 500g 1kg 2kg",
                price: 5.29,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates ceat esse.",
                img: "img/others/others005.jpg",
            },
            {
                id: 5,
                title: "Eastern Global Ergonoic Laptop Stand",
                price: 12.67,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates ceat esse.",
                img: "img/others/others006.jpg",
            },
            {
                id: 6,
                title: "Hight Quality Neck Pillow",
                price: 7.52,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates ceat esse.",
                img: "img/others/others007.jpg",
            },
            {
                id: 7,
                title: "LED Temperature Display mart Stelel Vacuum",
                price: 8.0,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates ceat esse.",
                img: "img/others/others008.jpg",
            },
            {
                id: 8,
                title: "Newest Electrical travel Adaptor Socket",
                price: 7.52,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates ceat esse.",
                img: "img/others/others009.jpg",
            },
            {
                id: 9,
                title: "Custom DOt COol Off Road Helmet ",
                price: 5.04,
                detail: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, quo. Maiores molestias, blanditiis provident voluptates ceat esse.",
                img: "img/others/others010.jpg",
            },
        ],
    },
];